### ISSUE TITLE
Craft 4 compatibility

### ISSUE THREAD

**Issue by AndrewMac** [webburo-spring/craft-spring-pixabay#10]
Hi there, just wondering if you could confirm whether you have any plans to update this for Craft 4?
Thanks in advance, Andrew

**Comment by rhlt** [comment]
Hi,
This should be done in the future, however, we aren't using Craft 4 for our own projects yet.
I'll keep this open to give notice when Craft 4 is supported.

**Comment by AndrewMac-UTS** [comment]
Hello again, and thanks for taking the time to reply, and for clarifying that you won't even be thinking about updating the plugin until you're using Craft 4 yourself. From my point of view, though, I would understand that position if you were offering the plugin for free, but I hope you can understand in turn that it disappoints me as a customer who has paid for the plugin. I mean, I'm glad to know your position … but that position is enough to make me start thinking about dropping the plugin and looking for alternatives. 

Not trying to start an argument or anything, by the way, just letting you know my thoughts … So thanks again for letting me know the position.

**Comment by rhlt** [comment]
The plugin has been updated for compatibility with Craft 4 in version 1.2.0
